title: Научные достижения России
description: От XIX века до СССР

remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

navbar:
  links:
    - name: "Таймлайн"
      url: "/timeline.html"