title: Научные достижения России
description: От XIX века до СССР
theme: jekyll-theme-merlot

plugins:
  - jekyll-remote-theme

navbar:
  links:
    - name: "Таймлайн"
      url: "/timeline.html"

# Разрешаем iframe и другие настройки безопасности
security:
  allowed_iframe_sources:
    - cdn.knightlab.com