title: Научные достижения России
description: От XIX века до СССР
theme: jekyll-theme-minimal

plugins:
  - jekyll-remote-theme

# Разрешаем iframe и другие настройки безопасности
security:
  allowed_iframe_sources:
    - cdn.knightlab.com